/*
 * Script to parse task registration scan output and generate the task metadata registry.
 * 
 * Usage:
 *   node scripts/generate_task_registry.js tasks.log
 */

const fs = require('fs');
const path = require('path');

const logFile = process.argv[2] || 'tasks.log';

if (!fs.existsSync(logFile)) {
  console.error(`Log file not found: ${logFile}`);
  process.exit(1);
}

const content = fs.readFileSync(logFile, 'utf-8');
const lines = content.split('\n');

// Parse TASK_REGISTRY_SCAN lines
const taskRegistry = {};
const pluginStats = {};

for (const line of lines) {
  const match = line.match(/\[TASK_REGISTRY_SCAN\] taskType="([^"]+)" ownerPlugin="([^"]+)" title="([^"]*)"/);
  if (match) {
    const [, taskType, ownerPlugin, title] = match;
    taskRegistry[taskType] = {
      ownerPlugin,
      title: title || taskType,
    };
    
    // Count tasks per plugin
    pluginStats[ownerPlugin] = (pluginStats[ownerPlugin] || 0) + 1;
  }
}

console.log('=== Task Registry Summary ===\n');
console.log(`Total task types: ${Object.keys(taskRegistry).length}\n`);

console.log('Tasks per plugin:');
const sortedPlugins = Object.entries(pluginStats).sort((a, b) => b[1] - a[1]);
for (const [plugin, count] of sortedPlugins) {
  console.log(`  ${plugin}: ${count}`);
}

console.log('\n=== Generated TypeScript ===\n');

// Generate TypeScript
const tsContent = `/*
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by: node scripts/generate_task_registry.js
 * 
 * This file contains the static task metadata registry for lazy task loading.
 * It maps task types to their owner plugins, allowing Task Manager to know
 * which plugin to load when a task needs to be executed.
 */

export interface TaskMetadata {
  /** The plugin that owns/registers this task type */
  ownerPlugin: string;
  /** Human-readable title for the task */
  title: string;
}

/**
 * Static registry of all task types and their owner plugins.
 * This allows Task Manager to claim tasks without loading all plugins at startup.
 */
export const TASK_METADATA_REGISTRY: Record<string, TaskMetadata> = {
${Object.entries(taskRegistry)
  .map(([taskType, meta]) => `  '${taskType}': { ownerPlugin: '${meta.ownerPlugin}', title: '${meta.title.replace(/'/g, "\\'")}' },`)
  .join('\n')}
};

/**
 * Get all task types owned by a specific plugin.
 */
export function getTaskTypesForPlugin(pluginId: string): string[] {
  return Object.entries(TASK_METADATA_REGISTRY)
    .filter(([, meta]) => meta.ownerPlugin === pluginId)
    .map(([taskType]) => taskType);
}

/**
 * Get the owner plugin for a task type.
 */
export function getOwnerPlugin(taskType: string): string | undefined {
  return TASK_METADATA_REGISTRY[taskType]?.ownerPlugin;
}
`;

console.log(tsContent);

// Write to file
const outputPath = path.join(__dirname, '..', 'tmp', 'task_metadata_registry.ts');
fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, tsContent);
console.log(`\n=== Written to: ${outputPath} ===`);
